#source this file
unset MONGO_INITDB_ROOT_USERNAME
unset MONGO_INITDB_ROOT_PASSWORD
unset MONGO_DB_PATH
unset MONGO_DB_USERNAME
unset MONGO_DB_PASSWORD
unset MONGO_DB_DATABASE
unset MONG_DB_CONTAINER_NAME
printenv | grep MONGO 
