version: "3.8"
services:
  db:
    image: mongo:latest
    command: mongod --auth
    container_name: mongo_db
    user: 1000:1000
    ports:
      - 27017:27017
    volumes:
      - $MONGO_DB_PATH:/data
      - $MONGO_DB_PATH/db:/data/db
      - $MONGO_DB_PATH/configdb:/data/configdb
    environment:
      # these two are 'magic' defines that cause mongodb to
      # create an admin user with name and password
      # given root priveleges
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: "no"
